# Generated by Django 5.1.6 on 2025-03-09 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('name', models.CharField(max_length=255, verbose_name='Agency name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_external', models.BooleanField(default=False, verbose_name='Is external source')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_agencies', to=settings.AUTH_USER_MODEL, verbose_name='Agency Owner')),
                ('staff', models.ManyToManyField(blank=True, related_name='staffed_agencies', to=settings.AUTH_USER_MODEL, verbose_name='Agency Staff')),
            ],
            options={
                'verbose_name': 'Exchange Agency',
                'verbose_name_plural': 'Exchange Agencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble')], max_length=3, verbose_name='Currency')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy Rate')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sell Rate')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_rates', to='application.exchangeagency', verbose_name='Exchange Agency')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'unique_together': {('agency', 'currency')},
            },
        ),
    ]
