# Generated by Django 5.1.6 on 2025-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeagency',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Agency name'),
        ),
    ]
