# Generated by Django 5.1.6 on 2025-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_exchangeagency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='buy_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Buy Rate'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('CNY', 'China Yuan'), ('USD-CNY', 'USD - Yuan (美元)')], max_length=7, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='sell_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sell Rate'),
        ),
    ]
